name: radio-registry-prod

services:
  radio-registry:
    build: .
    image: ${CONTAINER_REGISTRY_REPO}/radio-registry:latest
    container_name: radio-registry
    restart: unless-stopped
    networks:
      - radio-net
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SSL_KEYSTORE_PATH=/app/keystore.p12
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    volumes:
      - ./certs/keystore.p12:/app/keystore.p12:ro