services:
  radio-registry:
    build: .
    image: ${CONTAINER_REGISTRY_REPO}/radio-registry:latest
    container_name: radio-registry
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env