services:
  radio-registry:
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SSL_KEYSTORE_PATH=/app/keystore.p12
    volumes:
      - ./certs/keystore.p12:/app/keystore.p12:ro