services:
  radio-registry:
    env_file:
      - .env.prod
    environment:
      - SSL_KEYSTORE_PATH=/app/keystore.p12
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
    ports:
      - "8443:8443"
    volumes:
      - ./certs/keystore.p12:/app/keystore.p12:ro