spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        default_schema: public
  test:
    database:
      replace: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: never
  otlp:
    metrics:
      export:
        enabled: false
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        enabled: false
        otlp:
          endpoint: http://localhost:4318/v1/traces

logging:
  structured:
    format:
      console: