spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: ${JPA_SHOW_SQL:false}

  test:
    database:
      replace: none

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration