spring:
  application:
    name: ${SPRING_APP_NAME:radio-registry}

  profiles:
    active: ${PROFILE_ACTIVE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}

    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        default_batch_fetch_size: ${HIBERNATE_DEFAULT_BATCH_FETCH_SIZE:20}

    show-sql: ${JPA_SHOW_SQL:true}

  data:
    web:
      pageable:
        default-page: ${DEFAULT_PAGE:0}
        default-page-size: ${DEFAULT_PAGE_SIZE:20}
        max-page-size: ${MAX_PAGE_SIZE:100}

#  security:
#    user:
#      name: ${SECURITY_USERNAME}
#      password: ${SECURITY_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: ${EXPOSURE_INCLUDE}

  endpoint:
    health:
      show-details: ${SHOW_DETAILS}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
    level:
      org:
        springframework:
          security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

server:
  port: 8080
  servlet:
    context-path: /api/v1