spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: false

    properties:
      hibernate:
        default_schema: public

  test:
    database:
      replace: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: never